spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          username: ${CONFIG_GIT_USER}
          password: ${CONFIG_GIT_PASSWORD}
          clone-on-start: true
          force-pull: true
          # Add this — tells JGit to skip SSH and use HTTPS auth
          skip-ssl-validation: false
          timeout: 10

logging:
  level:
    org:
      eclipse:
        jgit: DEBUG
      springframework:
        cloud:
          config:
            server: DEBUG

server:
  port: 8888
